# Generated by Django 3.1 on 2020-08-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('bill_for', models.CharField(max_length=20)),
                ('date_paid', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
