# Generated by Django 3.1.2 on 2020-10-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='id',
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
